#!/bin/bash

opt=$1
target=$1
server_port=$2
if [ ! $server_port ];then
   server_port=$1
fi


usage() {
	cat <<- EOF
	
	Usage: standalone [TARGET] [OPTIONS]
     
   OPTIONS:
      -h               -- print usage
      --server-port    -- change server port other then 8080
   TARGET:  spring.profiles.active=?, default to 'standalone'
      .         -- ignore config
      -         -- force rebuild: mvn clean
      name      -- no target, default to standalone
   e.g.
      standalone -h 
      standalone  
      standalone -
      standalone .
      standalone --server.port=8081
      standalone test 
	EOF
	exit
}
if [[ $opt == '-h' ]];then
  usage
fi
if [[ $opt == '-' ]];then
  mvn clean
fi

check_target=$(echo $target | grep '\-')
if [ $check_target ]; then
   target=standalone
fi

check_server_port=$(echo $server_port | grep '\-\-server.port=')
if [ $check_server_port ]; then
   server_port=$server_port
else
   server_port='--server.port=8080'
fi



readlink_fix=()
if [[ $(uname) == 'Darwin' ]]; then
   #dir=$(greadlink -f "$0")
   readlink_fix=greadlink
else
   #dir=$(readlink -f "$0")
   readlink_fix=readlink
fi

### start ###
dir=$($readlink_fix -f "$0")
dir=$(dirname $dir)

## check in target dir
targetdir=$(basename $PWD)
if [ $targetdir = 'target' ];then
   cd ..
fi

if [ ! -e ./pom.xml ];then
   cp -r $dir/pom_template.xml ./pom.xml
fi

standalone=$(ls *-standalone.jar app.jar 2> /dev/null)

## no standalone, build
if [ ! $standalone ];then
   if [ ! -d target ];then
      echo "1> mvn -DskipTests clean -DskipStandalone=false package"
      mvn -DskipTests clean -DskipStandalone=false package
   fi
fi

### skip config/application.yml
if [[ $target == '.' ]];then
   target=$target
else
   if [ ! -e config ];then
      mkdir config
   fi
   if [ ! -f ./config/application.yml ]; then
      cp $dir/standalone.yml ./config/application.yml
   fi

   ## mkdir config outside target
   if [ -e target/config ];then
      rm -rf target/config
   fi

   ## just when no standalone...
   if [ ! $standalone ];then
      if [ ! -e target/config ]; then
         mkdir target/config
      fi
   fi

   if [ ! $target ];then
      target=standalone
   fi

   if [ -e target/config ];then
      echo "cp config/application.yml target/config/application-$target.yml"
      cp ./config/application.yml target/config/application-$target.yml
   fi
fi

### run directly
standalone=$(ls *-standalone.jar app.jar 2> /dev/null)
if [ $standalone ];then
   echo "java -jar $standalone --spring.profiles.active=$target $server_port"
   java -jar $standalone --spring.profiles.active=$target $server_port

else

   ### root area
   standalone=$(ls target/*-standalone.jar target/app.jar 2> /dev/null)
   if [ ! $standalone ];then
      if [ -f pom.xml ];then
         echo "2> mvn clean -DskipStandalone=false package"
         mvn clean -DskipStandalone=false package
         standalone=$(ls target/*-standalone.jar target/app.jar 2> /dev/null)

         if [ $standalone ];then
            cd target
         else
            echo 'fail to build -standalone.jar => mvn clean package'
            exit
         fi
      fi
   fi

   standalone=$(ls *-standalone.jar app.jar 2> /dev/null)
   if [ ! $standalone ];then
      echo "no standalone jar exists !"
   else
      echo "java -jar $standalone --spring.profiles.active=$target $server_port"
      java -jar $standalone --spring.profiles.active=$target $server_port
   fi
   
fi