---
spring:
  profiles: standalone
  datasource:
      url: jdbc:mysql://go.smallsaas.cn:10080/test?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: rootAZaz123
      filters: log4j,wall,mergeStat
      sql-script-encoding: UTF-8
      schema: classpath*:sql/*-schema.sql
      data: classpath*:sql/*-data.sql
      initialize: false 

logging:
  level: debug
