version: '3.4'
services:
  cli:
    build:
      context: ../../../
      dockerfile: ./docker/tag/dicToExcel/Dockerfile
    environment: 
      HOST: gateway.host.smallsaas.cn
      PORT: 7336
      USERNAME: root
      PASSWORD: root
      DATABASE: alliance
    volumes: 
      - ./out:/var/tmp
      
